"""
List of past competitions, starting from 2021.
122 url's as of December 2nd 2022.
"""

CUP_SYSTEMS_WITH_PLAYER_PRIZES = [
    "https://old.siege.gg/competitions/297-six-invitational-2021?tab=results&stats=full-stats",
    "https://old.siege.gg/competitions/342-six-mexico-major-2021?tab=results&stats=full-stats",
    "https://old.siege.gg/competitions/365-six-sweden-major-2021?tab=results&stats=full-stats",
    "https://old.siege.gg/competitions/387-six-invitational-2022?tab=results&stats=full-stats",
    "https://old.siege.gg/competitions/404-six-charlotte-major-2022?tab=results&stats=full-stats",
    "https://old.siege.gg/competitions/418-six-berlin-major-2022?tab=results&stats=full-stats",
    "https://old.siege.gg/competitions/431-six-jonkoping-major-2022?tab=results&stats=full-stats",
    "https://old.siege.gg/competitions/376-european-league-2021-finals?tab=results&stats=full-stats",
    "https://old.siege.gg/competitions/375-north-american-league-2021-finals?tab=results&stats=full-stats",
    "https://old.siege.gg/competitions/373-brasileirao-2021-finals?tab=results&stats=full-stats",
]

LEAGUE_SYSTEMS_WITH_NO_PLAYER_PRIZES = {
    "EUROPE": [
        "https://old.siege.gg/competitions/309-benelux-league-season-6?tab=results&stats=full-stats",
        "https://old.siege.gg/competitions/312-gsa-league-2021?tab=results&stats=full-stats",
        "https://old.siege.gg/competitions/301-european-league-2021-stage-1?tab=results&stats=full-stats",
        "https://old.siege.gg/competitions/323-european-league-2021-stage-2?tab=results&stats=full-stats",
        "https://old.siege.gg/competitions/346-european-league-2021-stage-3?tab=results&stats=full-stats",
        "https://old.siege.gg/competitions/359-european-challenger-league-2021?tab=results&stats=full-stats",
        "https://old.siege.gg/competitions/377-european-league-2021-relegation?tab=results&stats=full-stats",
        "https://old.siege.gg/competitions/430-european-challenger-league-2022?stats=full-stats",
        "https://old.siege.gg/competitions/395-european-league-2022-stage-1?tab=results&stats=full-stats",
        "https://old.siege.gg/competitions/411-european-league-2022-stage-2?tab=results&stats=full-stats",
        "https://old.siege.gg/competitions/424-european-league-2022-stage-3?tab=results&stats=full-stats",
    ],
    "LATAM": [
        "https://old.siege.gg/competitions/306-campeonato-mexicano-2021-stage-1?tab=results&stats=full-stats",
        "https://old.siege.gg/competitions/304-campeonato-sudamericano-2021-stage-1?tab=results&stats=full-stats",
        "https://old.siege.gg/competitions/305-brasileirao-2021-stage-1?tab=results&stats=full-stats",
        "https://old.siege.gg/competitions/324-campeonato-sudamericano-2021-stage-2?tab=results&stats=full-stats",
        "https://old.siege.gg/competitions/326-campeonato-mexicano-2021-stage-2?tab=results&stats=full-stats",
        "https://old.siege.gg/competitions/325-brasileirao-2021-stage-2?tab=results&stats=full-stats",
        "https://old.siege.gg/competitions/352-campeonato-sudamericano-2021-stage-3?tab=results&stats=full-stats",
        "https://old.siege.gg/competitions/351-campeonato-mexicano-2021-stage-3?tab=results&stats=full-stats",
        "https://old.siege.gg/competitions/350-brasileirao-2021-stage-3?tab=results&stats=full-stats",
        "https://old.siege.gg/competitions/421-brasileirao-2022-stage-3?tab=results&stats=full-stats",
        "https://old.siege.gg/competitions/422-campeonato-mexicano-2022-stage-3?tab=results&stats=full-stats",
        "https://old.siege.gg/competitions/423-campeonato-sudamericano-2022-stage-3?tab=results&stats=full-stats",
        "https://old.siege.gg/competitions/406-brasileirao-2022-stage-2?tab=results&stats=full-stats",
        "https://old.siege.gg/competitions/407-campeonato-mexicano-2022-stage-2?tab=results&stats=full-stats",
        "https://old.siege.gg/competitions/408-campeonato-sudamericano-2022-stage-2?tab=results&stats=full-stats",
        "https://old.siege.gg/competitions/391-brasileirao-2022-stage-1?tab=results&stats=full-stats",
    ],
    "NA": [
        "https://old.siege.gg/competitions/307-north-american-league-2021-stage-1?tab=results&stats=full-stats",
        "https://old.siege.gg/competitions/320-north-american-league-2021-stage-2?tab=results&stats=full-stats",
        "https://old.siege.gg/competitions/349-north-american-league-2021-stage-3?tab=results&stats=full-stats",
        "https://old.siege.gg/competitions/390-north-american-league-2022-stage-1?tab=results&stats=full-stats",
        "https://old.siege.gg/competitions/396-north-american-challenger-league-2022-stage-1?tab=results&stats=full-stats",
        "https://old.siege.gg/competitions/434-north-american-challenger-league-2022-finals?tab=results&stats=full-stats",
        "https://old.siege.gg/competitions/420-north-american-league-2022-stage-3?tab=results&stats=full-stats",
        "https://old.siege.gg/competitions/405-north-american-league-2022-stage-2?tab=results&stats=full-stats",
    ],
    "APAC": [
        "https://old.siege.gg/competitions/303-apac-south-division-2021-stage-1?tab=results&stats=full-stats",
        "https://old.siege.gg/competitions/302-apac-north-division-2021-stage-1?tab=results&stats=full-stats",
        "https://old.siege.gg/competitions/321-apac-north-division-2021-stage-2?tab=results&stats=full-stats",
        "https://old.siege.gg/competitions/347-apac-north-division-2021-stage-3?tab=results&stats=full-stats",
        "https://old.siege.gg/competitions/348-apac-south-division-2021-stage-3?tab=results&stats=full-stats",
        "https://old.siege.gg/competitions/388-apac-north-division-2022-stage-1?tab=results&stats=full-stats",
        "https://old.siege.gg/competitions/389-apac-south-division-2022-stage-1?tab=results&stats=full-stats",
        "https://old.siege.gg/competitions/409-apac-north-division-2022-stage-2?tab=results&stats=full-stats",
        "https://old.siege.gg/competitions/410-apac-south-division-2022-stage-2?tab=results&stats=full-stats",
        "https://old.siege.gg/competitions/426-apac-north-division-2022-stage-3?tab=results&stats=full-stats",
        "https://old.siege.gg/competitions/427-apac-south-division-2022-stage-3?tab=results&stats=full-stats",
    ],
}

CUP_SYSTEMS_WITH_NO_PLAYER_PRIZES = {
    "EUROPE": [
        "https://old.siege.gg/competitions/310-pg-nationals-spring-2021?tab=results&stats=full-stats",
        "https://old.siege.gg/competitions/329-pg-nationals-spring-2021-finals?tab=results&stats=full-stats",
        "https://old.siege.gg/competitions/331-pg-nationals-2020-2021-finals?tab=results&stats=full-stats",
        "https://old.siege.gg/competitions/330-6-french-league-season-3?tab=results&stats=full-stats",
        "https://old.siege.gg/competitions/337-benelux-league-season-6-finals?tab=results&stats=full-stats",
        "https://old.siege.gg/competitions/318-polish-masters-2021?tab=results&stats=full-stats",
        "https://old.siege.gg/competitions/345-polish-masters-2021-finals?tab=results&stats=full-stats",
        "https://old.siege.gg/competitions/344-gsa-league-2021-finals?tab=results&stats=full-stats",
        "https://old.siege.gg/competitions/355-6-french-league-season-3-finals?tab=results&stats=full-stats",
        "https://old.siege.gg/competitions/357-pg-nationals-winter-2021?tab=results&stats=full-stats",
        "https://old.siege.gg/competitions/366-pg-nationals-winter-2021-finals?tab=results&stats=full-stats",
        "https://old.siege.gg/competitions/368-benelux-cup-season-2?tab=results&stats=full-stats",
        "https://old.siege.gg/competitions/380-benelux-cup-season-2-finals?tab=results&stats=full-stats",
        "https://old.siege.gg/competitions/383-six-invitational-2022-europe-qualifier?tab=results&stats=full-stats",
        "https://old.siege.gg/competitions/398-benelux-league-season-7?tab=results&stats=full-stats",
        "https://old.siege.gg/competitions/403-gsa-league-2022?tab=results&stats=full-stats",
        "https://old.siege.gg/competitions/414-benelux-league-season-7-finals?tab=results&stats=full-stats",
        "https://old.siege.gg/competitions/419-gsa-league-2022-finals?tab=results&stats=full-stats",
    ],
    "LATAM": [
        "https://old.siege.gg/competitions/284-six-invitational-2021-latin-america-qualifier?tab=results&stats=full-stats",
        "https://old.siege.gg/competitions/314-copa-elite-six-2021-stage-1?tab=results&stats=full-stats",
        "https://old.siege.gg/competitions/317-copa-do-brasil-2021-stage-1?tab=results&stats=full-stats",
        "https://old.siege.gg/competitions/336-copa-elite-six-2021-stage-2?tab=results&stats=full-stats",
        "https://old.siege.gg/competitions/340-copa-do-brasil-2021-stage-2?tab=results&stats=full-stats",
        "https://old.siege.gg/competitions/354-brasileirao-serie-b-2021?tab=results&stats=full-stats",
        "https://old.siege.gg/competitions/358-copa-elite-six-2021-stage-3?tab=results&stats=full-stats",
        "https://old.siege.gg/competitions/363-brasileirao-serie-b-2021-finals?tab=results&stats=full-stats",
        "https://old.siege.gg/competitions/362-copa-do-brasil-2021-stage-3?tab=results&stats=full-stats",
        "https://old.siege.gg/competitions/370-campeonato-mexicano-2021-relegation?tab=results&stats=full-stats",
        "https://old.siege.gg/competitions/369-brasileirao-2021-relegation?tab=results&stats=full-stats",
        "https://old.siege.gg/competitions/371-campeonato-sudamericano-2021-relegation?tab=results&stats=full-stats",
        "https://old.siege.gg/competitions/372-campeonato-sudamericano-2021-finals?tab=results&stats=full-stats",
        "https://old.siege.gg/competitions/374-campeonato-mexicano-2021-finals?tab=results&stats=full-stats",
        "https://old.siege.gg/competitions/436-copa-do-brasil-2022-stage-3?tab=results&stats=full-stats",
        "https://old.siege.gg/competitions/435-campeonato-mexicano-2022-finals?tab=results&stats=full-stats",
        "https://old.siege.gg/competitions/433-copa-elite-six-2022-stage-3?tab=results&stats=full-stats",
        "https://old.siege.gg/competitions/429-brasileirao-serie-b-2022?tab=results&stats=full-stats",
        "https://old.siege.gg/competitions/416-copa-do-brasil-2022-stage-2?tab=results&stats=full-stats",
        "https://old.siege.gg/competitions/415-copa-elite-six-2022-stage-2?tab=results&stats=full-stats",
        "https://old.siege.gg/competitions/401-copa-do-brasil-2022-stage-1?tab=results&stats=full-stats",
        "https://old.siege.gg/competitions/400-copa-elite-six-2022-stage-1?tab=results&stats=full-stats",
        "https://old.siege.gg/competitions/392-campeonato-mexicano-2022-stage-1?tab=results&stats=full-stats",
        "https://old.siege.gg/competitions/393-campeonato-sudamericano-2022-stage-1?tab=results&stats=full-stats",
        "https://old.siege.gg/competitions/382-six-invitational-2022-latin-america-qualifier?tab=results&stats=full-stats",
        "https://old.siege.gg/competitions/437-brasileirao-serie-b-2022-finals?tab=results&stats=full-stats",
    ],
    "NA": [
        "https://old.siege.gg/competitions/308-north-american-challenger-league-2021-stage-1?tab=results&stats=full-stats",
        "https://old.siege.gg/competitions/319-north-american-challenger-league-2021-stage-1-playoffs?tab=results&stats=full-stats",
        "https://old.siege.gg/competitions/328-north-american-challenger-league-2021-stage-2?tab=results&stats=full-stats",
        "https://old.siege.gg/competitions/343-north-american-challenger-league-2021-stage-2-playoffs?tab=results&stats=full-stats",
        "https://old.siege.gg/competitions/384-six-invitational-2022-north-america-qualifier?tab=results&stats=full-stats",
        "https://old.siege.gg/competitions/378-north-american-league-2021-relegation?tab=results&stats=full-stats",
        "https://old.siege.gg/competitions/364-north-american-challenger-league-2021-stage-3-playoffs?tab=results&stats=full-stats",
        "https://old.siege.gg/competitions/356-north-american-challenger-league-2021-stage-3?tab=results&stats=full-stats",
        "https://old.siege.gg/competitions/425-north-american-challenger-league-2022-stage-3?tab=results&stats=full-stats",
        "https://old.siege.gg/competitions/412-north-american-challenger-league-2022-stage-2?tab=results&stats=full-stats",
    ],
    "APAC": [
        "https://old.siege.gg/competitions/299-korean-open-spring-2021?tab=results&stats=full-stats",
        "https://old.siege.gg/competitions/313-korean-open-spring-2021-finals?tab=results&stats=full-stats",
        "https://old.siege.gg/competitions/316-apac-league-2021-stage-1-playoffs?tab=results&stats=full-stats",
        "https://old.siege.gg/competitions/315-apac-league-2021-stage-1-stage-champion?tab=results&stats=full-stats",
        "https://old.siege.gg/competitions/327-korean-open-summer-2021?tab=results&stats=full-stats",
        "https://old.siege.gg/competitions/332-korean-open-summer-2021-finals?tab=results&stats=full-stats",
        "https://old.siege.gg/competitions/322-apac-south-division-2021-stage-2?tab=results&stats=full-stats",
        "https://old.siege.gg/competitions/338-apac-league-2021-stage-2-playoffs?tab=results&stats=full-stats",
        "https://old.siege.gg/competitions/300-japan-league-2021?tab=results&stats=full-stats",
        "https://old.siege.gg/competitions/353-korean-open-autumn-2021?tab=results&stats=full-stats",
        "https://old.siege.gg/competitions/361-apac-league-2021-stage-3-playoffs?tab=results&stats=full-stats",
        "https://old.siege.gg/competitions/360-korean-open-autumn-2021-finals?tab=results&stats=full-stats",
        "https://old.siege.gg/competitions/381-six-invitational-2022-asia-pacific-qualifier?tab=results&stats=full-stats",
        "https://old.siege.gg/competitions/386-apac-south-division-2021-relegations?tab=results&stats=full-stats",
        "https://old.siege.gg/competitions/385-apac-north-division-2021-relegations?tab=results&stats=full-stats",
        "https://old.siege.gg/competitions/397-japan-league-2022-season-1?tab=results&stats=full-stats",
        "https://old.siege.gg/competitions/399-apac-league-2022-stage-1-playoffs?tab=results&stats=full-stats",
        "https://old.siege.gg/competitions/402-japan-league-2022-season-1-playoffs?tab=results&stats=full-stats",
        "https://old.siege.gg/competitions/413-japan-league-2022-season-2?tab=results&stats=full-stats",
        "https://old.siege.gg/competitions/417-japan-league-2022-season-2-playoffs?tab=results&stats=full-stats",
        "https://old.siege.gg/competitions/428-japan-league-2022-season-3?tab=results&stats=full-stats",
    ],
}
