from enum import auto, Enum

class Attack(Enum):
    """List of attack operators"""
    SLEDGE = auto()
    THATCHER = auto()
    ASH = auto()
    THERMITE = auto()
    TWITCH = auto()
    MONTAGNE = auto()
    GLAZ = auto()
    FUZE = auto()
    BLITZ = auto()
    IQ = auto()
    BUCK = auto()
    BLACKBEARD = auto()
    CAPITAO = auto()
    HIBANA = auto()
    JACKAL = auto()
    YING = auto()
    ZOFIA = auto()
    DOKKAEBI = auto()
    LION = auto()
    FINKA = auto()
    MAVERICK = auto()
    NOMAD = auto()
    GRIDLOCK = auto()
    NOKK = auto()
    AMARU = auto()
    KALI = auto()
    IANA = auto()
    ACE = auto()
    ZERO = auto()
    FLORES = auto()
    OSA = auto()
    SENS = auto()
    GRIM = auto()

class Defense(Enum):
    """List of defense operators"""
    SMOKE = auto()
    MUTE = auto()
    CASTLE = auto()
    PULSE = auto()
    DOC = auto()
    ROOK = auto()
    KAPKAN = auto()
    TACHANKA = auto()
    JAGER = auto()
    BANDIT = auto()
    FROST = auto()
    VALKYRIE = auto()
    CAVEIRA = auto()
    ECHO = auto()
    MIRA = auto()
    LESION = auto()
    ELA = auto()
    VIGIL = auto()
    ALIBI = auto()
    MAESTRO = auto()
    CLASH = auto()
    KAID = auto()
    MOZZIE = auto()
    WARDEN = auto()
    GOYO = auto()
    WAMAI = auto()
    ORYX = auto()
    MELUSI = auto()
    ARUNI = auto()
    THUNDERBIRD = auto()
    THORN = auto()
    AZAMI = auto()
