# Generated by Django 4.1.2 on 2022-10-31 23:43

from django.db import migrations


def create_data(apps, schema_editor):
    Profile = apps.get_model('api', 'Profile')
    Profile(user="therealrxfa", balance=0.00).save()

class Migration(migrations.Migration):
    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_data),
    ]
